// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestForOnlyOffice.Data;

namespace TestForOnlyOffice.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210702121650_First1")]
    partial class First1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("TestForOnlyOffice.Model.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f9278c77-4a5c-407b-95db-2d8736f2cd6c"),
                            Email = "alexmokhov@ya.ru",
                            FirstName = "Alex",
                            Language = "ru",
                            LastName = "Mokhov",
                            Password = "123456"
                        },
                        new
                        {
                            Id = new Guid("1f8e9a51-f987-4c06-b115-f031d8f941f0"),
                            Email = "mukhiv@ya.ru",
                            FirstName = "Vladimir",
                            Language = "ru",
                            LastName = "Mukhin",
                            Password = "123456"
                        },
                        new
                        {
                            Id = new Guid("1f459835-ea0e-4047-b7a5-250ee512d691"),
                            Email = "novikov@ya.ru",
                            FirstName = "Max",
                            Language = "ru",
                            LastName = "Novikov",
                            Password = "123456"
                        },
                        new
                        {
                            Id = new Guid("963fea18-f18e-48da-967a-012c8ce6c06a"),
                            Email = "ivanoff@ya.ru",
                            FirstName = "Ivan",
                            Language = "ru",
                            LastName = "Ivanov",
                            Password = "123456"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
